import { NextRequest, NextResponse } from "next/server";
export const dynamic = "force-dynamic";
const routes:Record<string,string>={na1:"americas",br1:"americas",la1:"americas",la2:"americas",oc1:"sea",euw1:"europe",eun1:"europe",tr1:"europe",ru:"europe",kr:"asia",jp1:"asia"};
const demo={demo:true,gameName:"Johnny",tagLine:"NA1",platform:"na1",level:287,profileIconId:29,rank:{tier:"PLATINUM",division:"II",leaguePoints:64,wins:82,losses:71},recent:{wins:6,losses:4,kda:3.18,games:10},champions:[{id:145,name:"Kai'Sa",slug:"Kaisa",masteryLevel:7,masteryPoints:184260,games:4,wins:3},{id:51,name:"Caitlyn",slug:"Caitlyn",masteryLevel:7,masteryPoints:132540,games:3,wins:2},{id:81,name:"Ezreal",slug:"Ezreal",masteryLevel:6,masteryPoints:98610,games:2,wins:1},{id:202,name:"Jhin",slug:"Jhin",masteryLevel:6,masteryPoints:74320,games:1,wins:0}]};
async function riot<T>(url:string,key:string):Promise<T>{const r=await fetch(url,{headers:{"X-Riot-Token":key},cache:"no-store"});if(!r.ok)throw new Error(r.status===404?"Player not found. Check the Riot ID, tag, and region.":`Riot API returned ${r.status}.`);return r.json() as Promise<T>}
export async function GET(req:NextRequest){const key=process.env.RIOT_API_KEY;const gameName=req.nextUrl.searchParams.get("gameName")?.trim();const tagLine=req.nextUrl.searchParams.get("tagLine")?.trim();const platform=req.nextUrl.searchParams.get("platform")?.toLowerCase()||"na1";if(!gameName||!tagLine)return NextResponse.json({error:"A Riot ID and tag are required."},{status:400});
const pythonApi=process.env.PYTHON_API_BASE_URL?.replace(/\/$/,"");
if(pythonApi){
  try{const upstream=await fetch(`${pythonApi}/api/player?gameName=${encodeURIComponent(gameName)}&tagLine=${encodeURIComponent(tagLine)}&platform=${encodeURIComponent(platform)}`,{cache:"no-store"});const body=await upstream.json();return NextResponse.json(upstream.ok?body:{error:body.detail||body.error||"The Python API request failed."},{status:upstream.status})}
  catch{return NextResponse.json({error:"The Python analytics service is temporarily unavailable."},{status:502})}
}
if(!key)return NextResponse.json({...demo,gameName,tagLine,platform});
try{const region=routes[platform]||"americas";const account=await riot<{puuid:string;gameName:string;tagLine:string}>(`https://${region}.api.riotgames.com/riot/account/v1/accounts/by-riot-id/${encodeURIComponent(gameName)}/${encodeURIComponent(tagLine)}`,key);
const [summoner,ranks,mastery,versions,ids]=await Promise.all([
riot<{summonerLevel:number;profileIconId:number}>(`https://${platform}.api.riotgames.com/lol/summoner/v4/summoners/by-puuid/${account.puuid}`,key),
riot<Array<{queueType:string;tier:string;rank:string;leaguePoints:number;wins:number;losses:number}>>(`https://${platform}.api.riotgames.com/lol/league/v4/entries/by-puuid/${account.puuid}`,key),
riot<Array<{championId:number;championLevel:number;championPoints:number}>>(`https://${platform}.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-puuid/${account.puuid}/top?count=8`,key),
fetch("https://ddragon.leagueoflegends.com/api/versions.json").then(r=>r.json() as Promise<string[]>),
riot<string[]>(`https://${region}.api.riotgames.com/lol/match/v5/matches/by-puuid/${account.puuid}/ids?start=0&count=10`,key)]);
const version=versions[0];const cj=await fetch(`https://ddragon.leagueoflegends.com/cdn/${version}/data/en_US/champion.json`).then(r=>r.json()) as {data:Record<string,{key:string;id:string;name:string}>};const cmap=new Map(Object.values(cj.data).map(c=>[Number(c.key),c]));
const matches=await Promise.all(ids.map(id=>riot<{info:{participants:Array<{puuid:string;championId:number;win:boolean;kills:number;deaths:number;assists:number}>}}>(`https://${region}.api.riotgames.com/lol/match/v5/matches/${id}`,key)));const players=matches.map(m=>m.info.participants.find(p=>p.puuid===account.puuid)).filter(Boolean) as Array<{championId:number;win:boolean;kills:number;deaths:number;assists:number}>;
const byChamp=new Map<number,{games:number;wins:number}>();for(const p of players){const c=byChamp.get(p.championId)||{games:0,wins:0};c.games++;if(p.win)c.wins++;byChamp.set(p.championId,c)}const wins=players.filter(p=>p.win).length;const kda=players.reduce((s,p)=>s+(p.kills+p.assists)/Math.max(1,p.deaths),0)/Math.max(1,players.length);const solo=ranks.find(r=>r.queueType==="RANKED_SOLO_5x5")||ranks[0];
return NextResponse.json({demo:false,gameName:account.gameName,tagLine:account.tagLine,platform,level:summoner.summonerLevel,profileIconId:summoner.profileIconId,rank:solo?{tier:solo.tier,division:solo.rank,leaguePoints:solo.leaguePoints,wins:solo.wins,losses:solo.losses}:null,recent:{wins,losses:players.length-wins,kda,games:players.length},champions:mastery.slice(0,5).map(m=>{const c=cmap.get(m.championId);return{id:m.championId,name:c?.name||`Champion ${m.championId}`,slug:c?.id||"Aatrox",masteryLevel:m.championLevel,masteryPoints:m.championPoints,...(byChamp.get(m.championId)||{games:0,wins:0})}})});
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"The Riot API request failed."},{status:502})}}
